# Concaténation de tableaux 

In [1]:
import numpy as np

In [2]:
vecteur1 = np.array([1,2,3,4])
vecteur2 = np.array([5,10,15,20,25,30,35,40])

In [3]:
vecteur = np.concatenate([vecteur1,vecteur2])

In [4]:
vecteur

array([ 1,  2,  3,  4,  5, 10, 15, 20, 25, 30, 35, 40])

In [5]:
matrice1 = np.array([[1,2,3],[4,5,6]])
matrice2 = np.array([[5,10,15],[20,25,30]])

In [6]:
matrice1

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
matrice2

array([[ 5, 10, 15],
       [20, 25, 30]])

In [8]:
matrice = np.concatenate((matrice1,matrice2), axis = 0)

In [9]:
matrice

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 5, 10, 15],
       [20, 25, 30]])

In [10]:
matrix = np.concatenate((matrice1,matrice2), axis = 1)

In [11]:
matrix

array([[ 1,  2,  3,  5, 10, 15],
       [ 4,  5,  6, 20, 25, 30]])

# Construction automatique des tableaux

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [16]:
np.ones((3,3), int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [17]:
np.full((2,5), 7, int)

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [18]:
np.full((5,5), 10, float)

array([[10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.]])

In [19]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

# La focntion diag()

In [21]:
matrice = np.arange(1,17).reshape(4,4)

In [22]:
matrice

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [23]:
np.diag(matrice, k=2)

array([3, 8])

In [24]:
np.diag(matrice, k=-2)

array([ 9, 14])

In [25]:
a = np.array([5,6,7,8,9])

In [26]:
a

array([5, 6, 7, 8, 9])

In [27]:
matrice_diagonale = np.diag(a)

In [28]:
matrice_diagonale

array([[5, 0, 0, 0, 0],
       [0, 6, 0, 0, 0],
       [0, 0, 7, 0, 0],
       [0, 0, 0, 8, 0],
       [0, 0, 0, 0, 9]])

In [29]:
matrice_diagonale1 = np.diag(a, k=-1)

In [30]:
matrice_diagonale1

array([[0, 0, 0, 0, 0, 0],
       [5, 0, 0, 0, 0, 0],
       [0, 6, 0, 0, 0, 0],
       [0, 0, 7, 0, 0, 0],
       [0, 0, 0, 8, 0, 0],
       [0, 0, 0, 0, 9, 0]])

# La fonction linspace()

In [31]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [32]:
np.linspace(0,5,6)

array([0., 1., 2., 3., 4., 5.])

In [33]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [34]:
np.arange(0,100,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

# Création de tableaux aléatoires 

In [35]:
np.random.rand(10)

np.random.rand(3,4)

array([[0.99077115, 0.6617098 , 0.50664176, 0.34485078],
       [0.40330806, 0.92549545, 0.37323298, 0.87949804],
       [0.23049136, 0.55140761, 0.489951  , 0.29015292]])

In [36]:
np.random.randn(6)

array([ 0.08079909, -0.139193  ,  0.32080075,  0.67212773, -0.20481112,
        0.82372874])

In [37]:
np.random.randn(4,4)

array([[ 0.76352385,  0.81721515,  1.14175256,  0.49012135],
       [-2.17551032,  0.17315892,  0.59204202,  0.50342752],
       [ 0.55599196, -0.33388072, -0.65831698,  1.29535744],
       [-1.21345585, -0.12705557,  0.48894118,  1.07956704]])

In [38]:
np.random.randint(1,100, 20)

array([24, 89, 31,  9, 64, 15, 41, 60, 98, 63, 77, 87, 51, 63, 75, 18, 54,
       20, 82, 45])

In [39]:
matrice = np.random.randint(0,20,(3,4))

In [40]:
matrice

array([[ 0,  4,  9,  2],
       [18, 19, 17, 16],
       [13, 11, 10,  1]])

In [41]:
x = np.random.normal(loc = 10, scale = 2, size=(3,4))

In [42]:
x

array([[13.52120034,  8.46072794, 12.33158199, 10.7238502 ],
       [10.78100052,  9.21534867,  5.51663475, 10.12711813],
       [ 8.63674874, 10.30399835,  9.08671714,  8.84879906]])

In [43]:
np.random.normal(15, 5, (5,5))

array([[13.57336945,  8.37167503,  1.57623368, 19.48274989, 12.63571588],
       [19.14814775, 12.78383415, 16.47281884, 14.77968293, 12.00044204],
       [11.2395113 , 26.67163832, 16.4365813 ,  9.53143894, 19.99810448],
       [22.12127514, 20.94981699, 15.99307521, 12.14734308,  5.49823567],
       [20.15064516, 12.0669008 , 19.07404812,  7.48852306, 10.18425784]])

In [44]:
np.random.normal(20,2,5)

array([22.56078618, 19.57222018, 24.20955799, 21.26076898, 18.6245558 ])