# Opérations d’algèbre linéaire avec Numpy

In [1]:
import numpy as np

In [2]:
vecteur1 = np.arange(0,11)

In [3]:
vecteur2 = np.arange(10,21)

In [4]:
vecteur1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
vecteur2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [6]:
vecteur1 + vecteur2

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [7]:
vecteur1 - vecteur2

array([-10, -10, -10, -10, -10, -10, -10, -10, -10, -10, -10])

In [8]:
vecteur1 * vecteur2

array([  0,  11,  24,  39,  56,  75,  96, 119, 144, 171, 200])

In [9]:
vecteur1 + 50

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60])

In [10]:
vecteur1 * 50

array([  0,  50, 100, 150, 200, 250, 300, 350, 400, 450, 500])

In [11]:
20/vecteur1

C:\Users\maham\AppData\Local\Temp\ipykernel_47888\4191997321.py:1: RuntimeWarning: divide by zero encountered in true_divide
  20/vecteur1


array([        inf, 20.        , 10.        ,  6.66666667,  5.        ,
        4.        ,  3.33333333,  2.85714286,  2.5       ,  2.22222222,
        2.        ])

In [12]:
20/vecteur2

array([2.        , 1.81818182, 1.66666667, 1.53846154, 1.42857143,
       1.33333333, 1.25      , 1.17647059, 1.11111111, 1.05263158,
       1.        ])

In [13]:
vecteur1/vecteur2

array([0.        , 0.09090909, 0.16666667, 0.23076923, 0.28571429,
       0.33333333, 0.375     , 0.41176471, 0.44444444, 0.47368421,
       0.5       ])

In [14]:
vecteur1 **2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [15]:
np.sqrt(vecteur1)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [16]:
np.exp(vecteur1)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [17]:
matrice1 = np.resize(np.arange(1,10),(3,3))

In [18]:
matrice1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
matrice2 = np.resize(np.arange(11,20),(3,3))

In [20]:
matrice2

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [21]:
matrice1 + matrice2

array([[12, 14, 16],
       [18, 20, 22],
       [24, 26, 28]])

In [22]:
produit_matrice = np.dot(matrice1, matrice2)

In [23]:
produit_matrice

array([[ 90,  96, 102],
       [216, 231, 246],
       [342, 366, 390]])

In [24]:
matrice1 * matrice2

array([[ 11,  24,  39],
       [ 56,  75,  96],
       [119, 144, 171]])

In [25]:
matrice1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
matrice_transpose = np.transpose(matrice1)

In [27]:
matrice_transpose

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [28]:
matrice1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
matrice_inv = np.linalg.inv(matrice1)

In [30]:
matrice_inv

array([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
       [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
       [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [31]:
det_matrice = np.linalg.det(matrice1)

In [32]:
det_matrice

-9.51619735392994e-16

In [33]:
propre_matrice = np.linalg.eig(matrice1)

In [34]:
propre_matrice

(array([ 1.61168440e+01, -1.11684397e+00, -3.38433605e-16]),
 array([[-0.23197069, -0.78583024,  0.40824829],
        [-0.52532209, -0.08675134, -0.81649658],
        [-0.8186735 ,  0.61232756,  0.40824829]]))