# Méthodes de calcul sur les arrays et l’argument axis

In [1]:
import numpy as np

In [2]:
tab = np.random.randint(0,100,15)

In [3]:
tab

array([78, 34, 75, 20, 91, 59, 22, 27, 28, 17, 81, 96, 88, 42, 18])

In [4]:
tab.max()

96

In [5]:
tab.argmax()

11

In [6]:
arr = np.random.randint(0,200,25)

In [7]:
arr

array([165, 123, 160, 128,  15, 182, 140,  44, 139,  43,  13,  95,  60,
       151, 168, 195, 117,  91, 115, 144,   3, 123,  78, 149, 172])

In [8]:
matrix = arr.reshape(5,5)

In [9]:
matrix

array([[165, 123, 160, 128,  15],
       [182, 140,  44, 139,  43],
       [ 13,  95,  60, 151, 168],
       [195, 117,  91, 115, 144],
       [  3, 123,  78, 149, 172]])

In [10]:
matrix.max(axis=0)

array([195, 140, 160, 151, 172])

In [11]:
matrix.max(axis=1)

array([165, 182, 168, 195, 172])

In [12]:
matrix.max()

195

In [13]:
matrix.min()

3

In [14]:
matrix.min(axis=0)

array([  3,  95,  44, 115,  15])

In [15]:
matrix.min(axis=1)

array([15, 43, 13, 91,  3])

In [16]:
matrix.mean(axis=0)

array([111.6, 119.6,  86.6, 136.4, 108.4])

In [17]:
matrix.mean(axis=1)

array([118.2, 109.6,  97.4, 132.4, 105. ])

In [18]:
matrix.mean()

112.52

In [19]:
matrix.sum()

2813

In [20]:
matrix.sum(axis = 0)

array([558, 598, 433, 682, 542])

In [21]:
matrix.sum(axis=1)

array([591, 548, 487, 662, 525])

In [22]:
matrix.std()

54.6465881826121

In [23]:
matrix.std(axis=0)

array([85.18121859, 14.49965517, 40.0079992 , 13.46996659, 66.12896491])

In [24]:
matrix.std(axis=1)

array([54.23430649, 56.15905982, 57.2454365 , 35.51675661, 59.80300996])