# Création de vecteurs à partir de listes

In [1]:
my_list = [1,2,3]

In [2]:
my_list

[1, 2, 3]

In [3]:
import numpy as np

In [4]:
np.array(my_list)

array([1, 2, 3])

In [5]:
tab = np.array(my_list)

In [6]:
tab

array([1, 2, 3])

In [7]:
type(tab)

numpy.ndarray

In [8]:
liste1 = [1,2, "Amine"]

In [9]:
liste1

[1, 2, 'Amine']

In [10]:
tab1 = np.array(liste1)

In [11]:
tab1

array(['1', '2', 'Amine'], dtype='<U11')

In [12]:
liste2 = [1,2, 3.6, 5.89, 10]

In [13]:
tab2 = np.array(liste2)

In [14]:
tab2

array([ 1.  ,  2.  ,  3.6 ,  5.89, 10.  ])

# Création de matrices : tableaux bidimensionnels

In [15]:
liste_listes = [[1,2,3], [4,5,6],[7,8,9]]

In [16]:
liste_listes

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [17]:
matrice1=np.array(liste_listes)

In [18]:
matrice1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
liste_listes2 = [[1,2], [3,4],[5,6]]

In [20]:
liste_listes2

[[1, 2], [3, 4], [5, 6]]

In [21]:
matrice2 = np.array(liste_listes2)

In [22]:
matrice2

array([[1, 2],
       [3, 4],
       [5, 6]])

# Création de tableaux de 3 dimensions

In [23]:
liste_listes_listes = [[[1,2],[3,4]], [[5,6],[7,8]]]

In [24]:
tab3 = np.array(liste_listes_listes)

In [25]:
tab3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [26]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [28]:
np.arange(5,20,2)

array([ 5,  7,  9, 11, 13, 15, 17, 19])

In [29]:
np.arange(10,101,5)

array([ 10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,  70,
        75,  80,  85,  90,  95, 100])

In [30]:
np.arange(30,9,-2)

array([30, 28, 26, 24, 22, 20, 18, 16, 14, 12, 10])

In [31]:
np.arange(5.0)

array([0., 1., 2., 3., 4.])

# Principaux attributs pour décrire un objet array 

In [32]:
vecteur1 = np.arange(5)

In [33]:
vecteur1

array([0, 1, 2, 3, 4])

In [34]:
vecteur1.ndim

1

In [35]:
np.ndim(vecteur1)

1

In [36]:
matrice1 = np.array([[0,1,2,3,4], [5,6,7,8,9],[10,11,12,13,14]])

In [37]:
matrice1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [38]:
matrice1.ndim

2

In [39]:
np.ndim(matrice1)

2

In [40]:
vecteur1.shape

(5,)

In [41]:
matrice1.shape

(3, 5)

In [42]:
np.shape(matrice1)

(3, 5)

In [43]:
vecteur1.size

5

In [44]:
np.size(vecteur1)

5

In [45]:
np.size(matrice1)

15

In [46]:
matrice1.size

15

# La méthode reshape()

In [47]:
a = np.arange(12)

In [48]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [49]:
a.shape

(12,)

In [50]:
b = a.reshape((3,4))

In [51]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [52]:
c = a.reshape((4,3))

In [53]:
c

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [54]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [55]:
d = a.reshape((2,5))

ValueError: cannot reshape array of size 12 into shape (2,5)

In [ ]:
tab = np.arange(15)

In [ ]:
tab

In [ ]:
tab.resize((3,5))

In [ ]:
tab

In [ ]:
tab2 = np.arange(12)

In [ ]:
tab2

In [ ]:
tab2.resize((2,5))

In [ ]:
tab2.resize((2,5), refcheck = False)

In [ ]:
tab2

In [ ]:
tab3 = np.arange(9)

In [ ]:
tab3

In [ ]:
tab3.resize((5,6), refcheck = False)

In [ ]:
tab3

In [ ]:
tab4 = np.arange(9)

In [ ]:
tab4

In [ ]:
m = np.resize(tab4,(5,6))

In [ ]:
m